### ISSUE TITLE
A Clear How we can help section

### ISSUE THREAD

**Issue by judewoolls** [judewoolls/assessment-project-1#2]
**User Story:** 
As a visitor, I want to understand the purpose of the website, so I can see how it can help me with mental health awareness.

**Acceptance Criteria:**

- [x] The homepage has a clear, concise mission statement.
- [x] A "How We Can Help" section is visible on the homepage.

**Tasks:**

- [x] Write and add a mission statement to the homepage.
