### ISSUE TITLE
Support Page

### ISSUE THREAD

**Issue by judewoolls** [judewoolls/assessment-project-1#3]
**User Story:** 
As a visitor, I want access to emergency contacts and support services, so I can get immediate help if needed.

**Acceptance Criteria:**

- [x] An "Emergency Contacts" link is prominently displayed.
- [x] The emergency contacts page lists at least 3 reliable support services.

**Tasks:**

- [x] Research reputable mental health support services.
- [x] Create and design an emergency contacts page. (support page)
